language: cpp
jobs:
  include:
  - os: linux
    script:
    - cmake -H. -B_build
    - cmake --build _build
    - cd _build
    - cpack -G DEB
    - cd ..
addons:
  apt:
    packages:
      - cmake
      - cmake-data
      - rpm
